/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package bank;

import org.junit.jupiter.api.Test;
import org.springframework.boot.test.context.SpringBootTest;

@SpringBootTest
class AppTest {
	@Test
	void contextLoads() {
	}
}
