/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package bank;

import bank.Adapters.out.PostgresJDBC.CustomerDaoAdapter;
import org.springframework.boot.SpringApplication;
import org.springframework.boot.autoconfigure.SpringBootApplication;
import org.springframework.context.ApplicationContext;
import org.springframework.context.annotation.AnnotationConfigApplicationContext;
import org.springframework.context.annotation.Configuration;
import org.springframework.data.jpa.repository.config.EnableJpaRepositories;

@SpringBootApplication
@EnableJpaRepositories
public class BankApplication {
    public static void main(String[] args) {
        SpringApplication.run(BankApplication.class, args);


    }
}
